### ISSUE TITLE
Support only changing gamma for single screen

### ISSUE THREAD

**Issue by leftshift** [mherzberg/wlr-brightness#1]
I'm using this to control the brightness of my OLED display which works quite nicely, thanks!
I did notice one slight issue though: When I attach an external monitor, the gamma also gets applied to that display, which is not really what I want.
It'd be nice to limit the displays wlr-brightness affects, maybe with a command line option?

**Comment by mherzberg** [comment]
Sounds useful, unfortunately I haven't really used this project in years so I will archive it to make that visible.
