### ISSUE TITLE
add gammastep compatibility

### ISSUE THREAD

**Issue by unmellow** [mherzberg/wlr-brightness#4]
if i start wlr-brightness while gammastep is running gammastep no longer controls  screen temperature
if i try to do the inverse gammastep while fail to launch t he first time and the second time it will control the temperature
correctly but wlr-brightness will no longer control the brightness 
could is it possible for both programs to coexist? I am desperate as all other brightness control programs i tried 
do not work

equivalent gammastep issue: [#46](https://gitlab.com/chinstrap/gammastep/-/issues/46)

**Comment by CameronNemo** [comment]
This is not really possible because both programs want full control over the gamma values.
