### ISSUE TITLE
Differerence to 5.12 kernel brightness feature

### ISSUE THREAD

**Issue by clotodex** [mherzberg/wlr-brightness#5]
Since brightness of OLED panels can now be controlled through "traditional" means again (see Kernel 5.12) - what is the benefit of this repository?
- is the gamma control vs what the kernel does any different (I don't know much here)
- is the main benefit now to be integrated into the wayland ecosystem through dbus?

I love the work done in this repository! Just wondering :)

**Comment by mherzberg** [comment]
Thanks for the question. I haven't looked at OLED brightness control for a while, as my approach didn't work after I switched from Sway to Wayland Gnome so I gave up on trying to control the brightness. I don't know much about the "5.12 kernel brightness feature", and a quick search didn't yield useful results I'm afraid. `wlr-brightness` simply uses the well-known hack of changing gamma values to lower the brightness. Once there is proper support built into the kernel, I don't see why anyone would need to use a solution like the one in this repo. I don't think the dbus interface would be enough reason to keep using it.
